export const AWARDS = [
    {id:"1UodR-B1P6Ijsu0zaQN83fwrmbSrsJRUY", issuer:"USK Investment Club", title:"Juara I — Research Report Competition (UNICFEST 2024)", date:"18 Nov 2024", rank:"1st Place"},
    {id:"1U8DT7khP5Oo3hbPAApBPlSNdOVpvQy85", issuer:"Kemendikbudristek · PIMNAS 37", title:"Juara Favorit — PKM-Riset Eksakta", date:"18 Oct 2024", rank:"Favorite"},
    {id:"16lGfEcE2fPP06lh8bxVVZWa0ZmfCNiZS", issuer:"Himasta USK", title:"Juara I — Big Data Competition (Statistics Explore 2024)", date:"19 Sep 2024", rank:"1st Place"},
    {id:"1B1zK6DiXJW03bCLmjiP1l7CbHWt7Cbah", issuer:"Diktiristek · PKM 2024", title:"Research Proposal Funding Recipient (PKM-RE)", date:"19 Aug 2024", rank:"Funded"}
  ];

export const CERTS = [
    {id:"1t7hv0f9yRTs6UuJaenH_QQ2-IBopARbs", issuer:"BNSP", title:"Ahli K3 Listrik (Electrical OSH Expert)", date:"14 Apr 2026"},
    {id:"1KbZR9YE8fofpsLEMwnkPSySlJDGc9o06", issuer:"Google · Bangkit", title:"Distinction Graduate — Machine Learning", date:"10 Jul 2024"},
    {id:"1Cg1Uw7IcwUu5hnnZP0HP91ml9JaRbPy4", issuer:"Dicoding", title:"Belajar Analisis Data dengan Python", date:"10 Mar 2024"},
    {id:"1W1OAe1jBOLSQU3GlWf42BGbpxGWiJeMg", issuer:"Google · Coursera", title:"Foundations of Project Management", date:"24 Jul 2022"},
    {id:"1p1B9KXV01QLkjvTMF5RQUJGU7VqdhxiF", issuer:"Google · Coursera", title:"Project Initiation: Starting a Successful Project", date:"27 Jul 2022"},
    {id:"1LhLzbv2t-RhXG-uaL7GnbgTvKSxZc0tE", issuer:"Google · Coursera", title:"Project Planning: Putting It All Together", date:"05 Sep 2022"},
    {id:"1u6dCyv74dUBawV8DrqMPItkq6k4xszP3", issuer:"Taalenta Digital", title:"PLTS On-Grid 1.8 MWp — Design & Simulation", date:"22 Dec 2025"},
    {id:"1Lzy8Mzh53xoC3N2V2I7JoRaBPzLRNIxr", issuer:"ATI Engineering Academy", title:"Electrical Engineering — Oil & Gas", date:"2026"},
    {id:"1wWQdL16rPjqn8_rNxRMTSpehsRkw3nfO", issuer:"ATI Engineering Academy", title:"Power System Analysis — Intermediate", date:"2026"},
    {id:"1VxdwqU4w5wrOd2zlkeYBdYZNoWtyvR1V", issuer:"ATI Engineering Academy", title:"Power System Analysis — Basic", date:"2026"},
    {id:"1K1khN8CY6HDgz1-kM1xHfyZSG9I6_w-V", issuer:"PT Perta Arun Gas", title:"Internship Completion (PKL)", date:"23 Jan 2024"}
  ];

export const MORE = [
    {id:"1xind1T0cc-QLQwEX92ktjyrqIleAVboa", issuer:"Google · Coursera", title:"Introduction to Git and GitHub", date:"2024"},
    {id:"1zeAfsc7jyhz1Vm6P9SD35zPXF2GlEI9I", issuer:"Google · Coursera", title:"Crash Course on Python", date:"2024"},
    {id:"12rND20tP_54B-ZOYmwh24JVUIpdiNE4E", issuer:"Google · Coursera", title:"Process Data from Dirty to Clean", date:"2024"},
    {id:"16PHkLscfmRThgleQy_Q3mZsIJSQBrrA2", issuer:"Google · Coursera", title:"Analyze Data to Answer Questions", date:"2024"},
    {id:"1p2KRZoILVi3kCQIViuHYEDEiSOEZPVzj", issuer:"Google · Coursera", title:"Share Data Through the Art of Visualization", date:"2024"},
    {id:"1P-JH6SOX4QvAEku00nySsvkoijv9IKNN", issuer:"Google · Coursera", title:"Using Python to Interact with the Operating System", date:"2024"},
    {id:"1Dh26GUuIVh7s4ZPTlYRWVmL0O5FtfMfq", issuer:"DeepLearning.AI · Stanford", title:"Machine Learning Specialization", date:"2024"},
    {id:"1MsMCir9iGQmn8Dpd9t_RBtKNdULwncTN", issuer:"DeepLearning.AI · Stanford", title:"Supervised Machine Learning: Regression and Classification", date:"2024"},
    {id:"19Cv1hIJp6d4llOEup-PxDayr_9H4M1T9", issuer:"DeepLearning.AI · Stanford", title:"Advanced Learning Algorithms", date:"2024"},
    {id:"1ommNa0L5Gr-e0laI4qoeKvRRjTYsqHqw", issuer:"DeepLearning.AI · Stanford", title:"Unsupervised Learning, Recommenders, Reinforcement Learning", date:"2024"},
    {id:"1nFAsZ0zvkK-DBk71MvM9a-ZA2rF1LgyG", issuer:"DeepLearning.AI", title:"Mathematics for Machine Learning and Data Science (Specialization)", date:"2024"},
    {id:"1vIjNiPHa9E8dU7-dgMafOJXtqCHkCpAa", issuer:"DeepLearning.AI", title:"Linear Algebra for Machine Learning and Data Science", date:"2024"},
    {id:"18ZD7z2htc60bEFWEH3pB_WjmNcv1Ona5", issuer:"DeepLearning.AI", title:"Calculus for Machine Learning and Data Science", date:"2024"},
    {id:"1LywCBL8ZLsWbmdJEDT8RPcdAOxbJBGOR", issuer:"DeepLearning.AI", title:"Probability & Statistics for Machine Learning & Data Science", date:"2024"},
    {id:"1ZYT9o-TD2z2g35ioayaBhtGixn_vkOqA", issuer:"DeepLearning.AI", title:"DeepLearning.AI TensorFlow Developer (Professional Certificate)", date:"2024"},
    {id:"1co3UCFc87bS4TgoVpMJYzKveqQo-AR50", issuer:"DeepLearning.AI", title:"Introduction to TensorFlow for AI, ML, and Deep Learning", date:"2024"},
    {id:"1CG1Pwatj9fiLSECjmygfDeiZhbMbwb40", issuer:"DeepLearning.AI", title:"Convolutional Neural Networks in TensorFlow", date:"2024"},
    {id:"1HCTK9OZCmlaSWZqy5KDT4Tx8K_P4_0Vo", issuer:"DeepLearning.AI", title:"Natural Language Processing in TensorFlow", date:"2024"},
    {id:"12PIzVH0M6PzYRy2DVXxbfWTMlyxR4EYh", issuer:"DeepLearning.AI", title:"Sequences, Time Series and Prediction", date:"2024"},
    {id:"1eMhN6OxTsN7G5wHK2nFSrWG8fQ-HkUYD", issuer:"DeepLearning.AI", title:"TensorFlow: Data and Deployment (Specialization)", date:"2024"},
    {id:"1h8z6OHLxAzytA59ll3HJsOWaSOAnYAxd", issuer:"DeepLearning.AI", title:"Browser-based Models with TensorFlow.js", date:"2024"},
    {id:"1v7k0tZTED3PqN9UqoipymhpfNhCTOCG5", issuer:"DeepLearning.AI", title:"Device-based Models with TensorFlow Lite", date:"2024"},
    {id:"1sXhXbauRilXm2zmwI13D0Nr-UkDiLLuU", issuer:"DeepLearning.AI", title:"Data Pipelines with TensorFlow Data Services", date:"2024"},
    {id:"11LYLv7creD_BxJ2mcqRj5hCtRKNNSk3P", issuer:"DeepLearning.AI", title:"Advanced Deployment Scenarios with TensorFlow", date:"2024"},
    {id:"1l1m7Pjmhpbxwb-eOdOoMNaUsupcvh1H5", issuer:"DeepLearning.AI", title:"Structuring Machine Learning Projects", date:"2024"},
    {id:"12glIExXpM4t6Srqua5RffOLdARIEwcdU", issuer:"DeepLearning.AI", title:"TensorFlow: Advanced Techniques (Specialization)", date:"2024"},
    {id:"1dhKxSScEMbSfVL7mA7TLYk697T_6oMPc", issuer:"DeepLearning.AI", title:"Custom and Distributed Training with TensorFlow", date:"2024"},
    {id:"1T_7fb47HrUSx9k8KF263c6IoOnb1HWkg", issuer:"DeepLearning.AI", title:"Custom Models, Layers, and Loss Functions with TensorFlow", date:"2024"},
    {id:"1SZROuGIsDnZRASITQcvcAAluyWKBKNQ6", issuer:"DeepLearning.AI", title:"Advanced Computer Vision with TensorFlow", date:"2024"},
    {id:"1LWJY3BmaMiWlK96zA0KVrOeykHi1wIZE", issuer:"DeepLearning.AI", title:"Generative Deep Learning with TensorFlow", date:"2024"},
    {id:"1hQCfCVYR9F7WEDqCSFd1yjZM1J7f81P2", issuer:"DeepLearning.AI", title:"Generative AI for Everyone", date:"2024"},
    {id:"1CIteXMNJcd7tOCnP703N5N9udVhJTVET", issuer:"ICMF 2021", title:"Income Allocation 101", date:"2021"},
    {id:"1h9QX77TId7WBCG9ttjetpieXbzNuBde0", issuer:"ICMF 2021", title:"Finance and Data Science 101", date:"2021"},
    {id:"1xHP7D1IYEsIKvP-OzoVWu3bKOdA9ko5T", issuer:"ICMF 2021", title:"Manfaat dari Investasi Saham, Pasti Dapat?", date:"2021"},
    {id:"1JjYN5_fHtIYvqcHKXWxm1wBwl7msSQTr", issuer:"ICMF 2021", title:"Fintech & Masa Depan Perbankan?", date:"2021"},
    {id:"1KKydv11AHs-Vq48aN-DFztPev5NB_0AL", issuer:"ICMF 2021", title:"Market Maker? Atau Market Player?", date:"2021"},
    {id:"1XVNmhsyDabCUnvi_B8v88WznESUdmQnW", issuer:"ICMF 2021", title:"Technical Analysis 101", date:"2021"},
    {id:"1iB3278t0JtrGVFrziaukWnf9ptYPrGsU", issuer:"ICMF 2021", title:"Venture Capital 101", date:"2021"},
    {id:"1En918zGEHrFS7va-x1PiEwkYuSUBTjE5", issuer:"ICMF 2021", title:"Equity Research 101", date:"2021"},
    {id:"1E2Vrj9RIQh1UHmVc08XEn0Ds85H64XJp", issuer:"ICMF 2021", title:"Financial Planning 101", date:"2021"},
    {id:"1xbP9Ko1kg0D_9thTg6MyRAmnWuo2ehsl", issuer:"ICMF 2021", title:"Pahami Instrumen Pasar Modal Lewat Sertifikasi", date:"2021"},
    {id:"1TwLmxjxnxRAcymd49gIeLTO1TEDqPxYI", issuer:"ICMF 2021", title:"Sustainable Investing: More than Fundamentals", date:"2021"},
    {id:"1zVR1_XIDz1Z9-4xwSML68auMNbPNIt3Z", issuer:"ICMF 2021", title:"Fundamental Stock Analysis 101", date:"2021"},
    {id:"1MaLFJpemWJBQRiqWGhBe46Nw0Qeq6zxA", issuer:"ICMF 2021", title:"Breaking the Sandwich Generation Trap", date:"2021"},
    {id:"1adXT2ts9DCDbdpwYlbExjl3NOkAT6J7v", issuer:"ICMF 2021", title:"The Journey of a Fintech Start-up", date:"2021"},
    {id:"1g9T3xAqi81TM4swmr1zjqV21ohFHlcT2", issuer:"ICMF 2021", title:"Neo-Rural Bank in Indonesia's Digital Economy", date:"2021"},
    {id:"1yCJasVQSwjOt7IyF2ggVoDFhPKOt5qst", issuer:"ICMF 2021", title:"Peran Generasi Muda Membangun Perekonomian Negara", date:"2021"},
    {id:"1N1D7rQTLebTYL5Lu11s6bV9zFV8LPJit", issuer:"ICMF 2021", title:"Membangun Portofolio untuk Millennials", date:"2021"},
    {id:"16-DjHtPPAB1mH7V_Q5OUch3NFvWW85LC", issuer:"ICMF 2021", title:"Kesiapan Psikologis sebelum Masuk ke Pasar Modal", date:"2021"},
    {id:"1f8FXQ89YbbeYMe8H6FgdyuWWJeEtmJTv", issuer:"ICMF 2021", title:"Outlook Investasi setelah Masa Pandemi", date:"2021"},
    {id:"1UUTXs9fxBH5i-6MS8EbXV51WJlijy9UK", issuer:"ICMF 2021", title:"Membangun Pola Pikir Keuangan yang Lebih Baik", date:"2021"},
    {id:"1CRUO8LkAQIEEd_XLX3O8Pc6MIwNACxc5", issuer:"Financial Camp", title:"Financial Light 2022 — Completion", date:"2022"},
    {id:"1WyglbaRXvIr3q0QA8RM8kxCXGCCA_QOI", issuer:"Financial Light", title:"Financial Light 2022", date:"2022"},
    {id:"1ydBKeUQDS5P2gQalg1g10hCllc45wAU3", issuer:"Financial Camp", title:"Financial Camp — Participant", date:"2022"},
    {id:"1Z1SVGAiycmbUHKSdzyaY6X4QyYHKJFJ8", issuer:"INFEST FMIPA", title:"Olimpiade Komputer — Informatics Festival 2018", date:"2018"},
    {id:"1jH9RO4yJml91XDrr8M2V1hRmg8UfRsaZ", issuer:"SMAN 10 Fajar Harapan", title:"OSIS — Pengurus 2019/2020", date:"2020"},
    {id:"1a4S9Yg9SAtbatTgJXgV5ynKH7YOyNAZ4", issuer:"Kemendikbudristek · PIMNAS 37", title:"PKM-Riset Eksakta — Participant", date:"2024"}
  ];
